# ─────────────────────────────────────────────────────────────
#  reports/email_sender.py  —  Send HTML report via SMTP
# ─────────────────────────────────────────────────────────────

import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email                import encoders
from datetime             import datetime

from config.settings import (
    EMAIL_ENABLED, SMTP_HOST, SMTP_PORT,
    SMTP_USER, SMTP_PASSWORD,
    EMAIL_FROM, EMAIL_TO, EMAIL_SUBJECT,
)
from reports.report_builder import TestReport


def send_report(report: TestReport):
    """
    Build the HTML report and send it via SMTP.
    Safe to call even if EMAIL_ENABLED = False.
    """
    if not EMAIL_ENABLED:
        print("[Email] EMAIL_ENABLED=False — skipping email.")
        return

    print(f"[Email] Sending report to {EMAIL_TO} …")

    # ── Build HTML ────────────────────────────────────────────
    html_body = report.build_html()

    # ── Subject ───────────────────────────────────────────────
    subject = EMAIL_SUBJECT.format(
        status=report.overall_status,
        score=report.final_score,
    )

    # ── MIME message ─────────────────────────────────────────
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_FROM
    msg["To"]      = ", ".join(EMAIL_TO)

    # Plain text fallback
    plain = _build_plain(report)
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    # No screenshot attachments — clean email only

    # ── Send ──────────────────────────────────────────────────
    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.ehlo()
            server.starttls(context=context)
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())

        print(f"[Email] [OK] Report sent successfully.")
        print(f"[Email]   Subject : {subject}")
        print(f"[Email]   To      : {EMAIL_TO}")

    except smtplib.SMTPAuthenticationError:
        print("[Email] ✗ Authentication failed.")
        print("         Check SMTP_USER and SMTP_PASSWORD in config/settings.py")
        print("         For Gmail: use an App Password, not your regular password.")
        print("         Go to: https://myaccount.google.com/apppasswords")
    except smtplib.SMTPException as e:
        print(f"[Email] ✗ SMTP error: {e}")
    except ConnectionRefusedError:
        print(f"[Email] ✗ Could not connect to {SMTP_HOST}:{SMTP_PORT}")
    except Exception as e:
        print(f"[Email] ✗ Unexpected error: {e}")


def save_html_report(report: TestReport) -> str:
    """Save the HTML report to disk as a local file (always runs)."""
    ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{ts}_{report.overall_status}.html"
    html     = report.build_html()
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"[Report] [OK] HTML report saved -> {filename}")
    return filename


def _build_plain(report: TestReport) -> str:
    lines = [
        f"StepUp Automation Report",
        f"{'='*50}",
        f"Test      : {report.test_name}",
        f"Student   : {report.student_name}",
        f"Status    : {report.overall_status}",
        f"Score     : {report.final_score}",
        f"Duration  : {report.duration()}",
        f"Started   : {report.start_time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Finished  : {report.end_time.strftime('%Y-%m-%d %H:%M:%S') if report.end_time else 'N/A'}",
        f"",
        f"{'─'*50}",
        f"QUESTION DETAILS",
        f"{'─'*50}",
    ]
    for q in report.questions:
        lines.append(f"\nQ{q.number} [{q.q_type}] — {q.status.upper()}")
        lines.append(f"  Question : {q.question[:100]}")
        if q.choices:
            for i, c in enumerate(q.choices):
                lines.append(f"    {chr(65+i)}) {c}")
        lines.append(f"  GPT Ans  : {q.gpt_answer}")

    lines += ["", "─"*50, "Generated by StepUp Automation Suite"]
    return "\n".join(lines)
